spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_management_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: true

server:
  port: 8080

person-management:
  default-page-size: 10
  batch-size: 50
