spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_management_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

logging:
  level:
    root: INFO
#    com.zaxxer.hikari: ERROR

server:
  port: 8080

person-management:
  default-page-size: 10
  batch-size: 5000